-- Migration: Create mapeos_excel_nomina table for saved Excel column mappings (Fase 1 - importacion nomina)
-- Path: supabase/migrations/20260721_create_mapeos_excel_nomina.sql

CREATE TABLE IF NOT EXISTS public.mapeos_excel_nomina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL REFERENCES public.contabot_empresas(id) ON DELETE CASCADE,
    huella_encabezados TEXT NOT NULL,        -- huella de los encabezados detectados en el Excel (para reusar el mapeo)
    mapeo JSONB NOT NULL,                    -- { encabezadoOriginal: campoDestino }
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_empresa_huella UNIQUE (empresa_id, huella_encabezados)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.mapeos_excel_nomina ENABLE ROW LEVEL SECURITY;

-- Solo miembros de la empresa (via usuarios_empresas) pueden leer/escribir sus mapeos
CREATE POLICY "Miembros de la empresa gestionan sus mapeos de Excel" ON public.mapeos_excel_nomina
    FOR ALL
    USING (
        empresa_id IN (
            SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        empresa_id IN (
            SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()
        )
    );
