-- Migration: Create whatsapp_numeros_autorizados table (intake de soportes via WhatsApp)
-- Path: supabase/migrations/20260722_create_whatsapp_numeros_autorizados.sql
-- NO APLICADA TODAVIA. Requiere aprobacion antes de ejecutar en Supabase.
--
-- Que hace: mapea un numero de WhatsApp (formato E.164 sin '+', ej '573001234567')
-- a la empresa_id correspondiente, para que el webhook sepa a que empresa pertenece
-- cada soporte que llega. Necesario para que un mismo numero de WhatsApp Business
-- pueda atender a varias empresas (multi-tenant).
--
-- Mientras esta migracion no se aplique, el webhook usa una sola empresa fija
-- via la variable de entorno WHATSAPP_TEST_EMPRESA_ID (solo para pruebas).

CREATE TABLE IF NOT EXISTS public.whatsapp_numeros_autorizados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL REFERENCES public.contabot_empresas(id) ON DELETE CASCADE,
    numero_whatsapp TEXT NOT NULL,           -- numero del remitente autorizado, formato E.164 sin '+'
    nombre_contacto TEXT,                    -- referencia humana, ej. "Nelly - SODEPORTC"
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_numero_whatsapp UNIQUE (numero_whatsapp)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.whatsapp_numeros_autorizados ENABLE ROW LEVEL SECURITY;

-- Solo miembros de la empresa (via usuarios_empresas) pueden ver/gestionar sus propios numeros autorizados
CREATE POLICY "Miembros de la empresa gestionan sus numeros de WhatsApp" ON public.whatsapp_numeros_autorizados
    FOR ALL
    USING (
        empresa_id IN (
            SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        empresa_id IN (
            SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()
        )
    );

-- Nota: el webhook de WhatsApp (app/api/whatsapp/webhook) usa la Service Role Key
-- (bypassa RLS) para leer esta tabla, ya que corre sin sesion de usuario autenticado.
