-- Registra cada abono individual contra una obligacion de nomina_programada.
-- Varias filas de esta tabla pueden ir completando una misma obligacion (abonos parciales),
-- y el saldo pendiente se calcula sumandolas, nunca se guarda en una columna manual.
--
-- receptor_pago: nombre de quien recibio fisicamente el dinero, SOLO si es distinto al
--                beneficiario (ej. pago a la cuenta de un familiar u otra persona autorizada).
--                Es unicamente informativo por ahora: no crea ninguna vinculacion automatica
--                ni cambia a quien pertenece la deuda.
-- referencia: llave de idempotencia para evitar contar el mismo comprobante dos veces
--             (ej. el media.id de WhatsApp, o un hash estable de la fila del Excel).
CREATE TABLE IF NOT EXISTS public.abonos_nomina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL REFERENCES public.contabot_empresas(id) ON DELETE CASCADE,
    obligacion_id BIGINT NOT NULL REFERENCES public.nomina_programada(id) ON DELETE CASCADE,
    valor_abonado NUMERIC NOT NULL CHECK (valor_abonado > 0),
    fecha_abono DATE NOT NULL DEFAULT CURRENT_DATE,
    referencia TEXT,
    receptor_pago TEXT,
    observaciones TEXT,
    origen TEXT NOT NULL DEFAULT 'manual' CHECK (origen IN ('excel','whatsapp','banco','manual')),
    archivo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_referencia_por_empresa UNIQUE (empresa_id, referencia)
);

ALTER TABLE public.abonos_nomina ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Miembros de la empresa gestionan abonos de nomina" ON public.abonos_nomina
    FOR ALL
    USING (empresa_id IN (SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()))
    WITH CHECK (empresa_id IN (SELECT empresa_id FROM public.usuarios_empresas WHERE user_id = auth.uid()));

CREATE INDEX IF NOT EXISTS idx_abonos_nomina_obligacion ON public.abonos_nomina (obligacion_id);
CREATE INDEX IF NOT EXISTS idx_abonos_nomina_empresa_fecha ON public.abonos_nomina (empresa_id, fecha_abono);
