-- Migration: Create alias_terceros table for ContaBot
-- Path: supabase/migrations/create_alias_terceros.sql

CREATE TABLE IF NOT EXISTS public.alias_terceros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    empresa_id UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,                    -- texto tal como aparece en el extracto bancario
    tercero_tipo TEXT NOT NULL CHECK (tercero_tipo IN ('empleado','familiar','proveedor','otro')),
    cedula TEXT,                             -- opcional: solo si tercero_tipo = 'empleado'
    tercero_nombre TEXT NOT NULL,            -- nombre confirmado por el auxiliar
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_empresa_alias UNIQUE (empresa_id, alias)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.alias_terceros ENABLE ROW LEVEL SECURITY;

-- Create security policies
CREATE POLICY "Users can manage their own aliases" ON public.alias_terceros
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
